# Generated by Django 6.0.5 on 2026-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_quiz_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(default='Multiple Choice', max_length=50),
        ),
    ]
